# Generated by Django 3.2.6 on 2021-11-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Pessoa')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('tipo', models.CharField(choices=[('C', 'Comercial'), ('F', 'Fixo'), ('P', 'Pessoal')], default='P', max_length=1, verbose_name='Tipo de telefone')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('numero', models.IntegerField(null=True, verbose_name='Número')),
                ('rua', models.CharField(max_length=200, null=True, verbose_name='Rua')),
                ('complemento', models.CharField(max_length=200, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, null=True, verbose_name='Estado')),
                ('sobre', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Pessoa')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('tipo', models.CharField(choices=[('C', 'Comercial'), ('F', 'Fixo'), ('P', 'Pessoal')], default='P', max_length=1, verbose_name='Tipo de telefone')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('numero', models.IntegerField(null=True, verbose_name='Número')),
                ('rua', models.CharField(max_length=200, null=True, verbose_name='Rua')),
                ('complemento', models.CharField(max_length=200, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, null=True, verbose_name='Estado')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
